version: '3.7'

services:

  logstash:
    image: tap:logstash
    networks: 
      - tap
    environment:
      XPACK_MONITORING_ENABLED: "false"
    volumes:
      - ./data_ingestion/logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    ports:
      - "5002:5002"
      
  coreradio_script:
    build: 
      context: ./data_ingestion/scrapers/coreradio_scraper
      dockerfile: Dockerfile
    networks:
      - tap
    volumes:
      - ./data_ingestion/scrapers/coreradio_scraper:/app
    depends_on:
      - logstash
    
    command: python3 /app/coreradio_scraper.py --output tcp://logstash:5002

networks:
  tap:
    name: tap
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.100.1/24
