version: '3.7'
services:
       
    logstash:
        image: tap:logstash
        networks: 
            - tap
        environment:
            XPACK_MONITORING_ENABLED: "false"
        volumes:
            - ./data_ingestion/scrapers/coreradio_scraper/json_files:/tmp/json_files
            - ./data_ingestion/logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
            - coreradio_output:/tmp/coreradio_output

#launch a python script that depends on logstash
    

    coreradio_script:
        build: 
            context: ./data_ingestion/scrapers/coreradio_scraper
            
        networks:
            - tap
        volumes:
            - ./data_ingestion/scrapers/coreradio_scraper:/app
            - coreradio_output:/app/output
        command: python3 /app/coreradio_scraper.py
        
volumes:
    coreradio_output: 


networks:
    tap:
        name: tap
        driver: bridge
        ipam:
            config:
                - subnet: 10.0.100.1/24