client_id = "bYn9RiVeg0XDsQxen_OhrpCqRIT3WFpUOP_cfxl41NPuybOtDzhzFDmasjiLHvgd"

client_secret = "_QzFD_y8v4ComT7DyDzEV7abtB7qTO2_k3GH3xk4G9cSb6ZpGVss5OfpM3rMwCxfteMOWj4lupVuG8b9jloTMQ"

access_token = "5eEqYSpR_WlDSv1johECV8bhePcZ-WxWxGacMWxXMzYgFhHNQWBxuDct1Fan9bYa"
